### Logistic regression

 - Logistic rergression is a supervised learning algorithm
 - Expresses the probability of one event taking place by having the logarithm of the event's odds be a linear combination of one or more independent variables
 - It outputs probabilities - if p>threshold the data label is 1, if p<threshold data label is 0 - the threshold is commonly 50% but can be adjusted
 - For p=0, the model predicts 1 for all data, if p=1 it predicts 0 for all data
 - Varying the threshold gives a series of true positives and false positive rates, this set is called the receiver operating characteristic curve
 - It produces a linear decision boundary
 - Learn more: https://en.wikipedia.org/wiki/Logistic_regression

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import scale

# Import the necessary modules
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

In [5]:
wines = load_wine()
features = pd.DataFrame(scale(wines['data']), columns = wines['feature_names'])
features.shape

(178, 13)

In [6]:
target = pd.DataFrame(wines['target'], columns=['Type'])
target.shape

(178, 1)

In [7]:
df = pd.concat([target,features],axis=1)
df.shape

(178, 14)

In [10]:
# Create arrays for the features and the response variable
y = target.values.reshape(-1)
X = features.values

display(y.shape, X.shape)

# Create training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.35,
                                                    random_state=42)

(178,)

(178, 13)

In [17]:
# Create the classifier: logreg
logreg = LogisticRegression()

# Fit the classifier to the training data
logreg.fit(X_train, y_train)

# Predict the labels of the test set: y_pred
y_pred = logreg.predict(X_test)

# Accuracy score
print('Accuracy', logreg.score(X_test,y_test), "\n")

# Compute and print the confusion matrix and classification report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))



Accuracy 0.9841269841269841 

[[21  0  0]
 [ 0 25  1]
 [ 0  0 16]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       1.00      0.96      0.98        26
           2       0.94      1.00      0.97        16

    accuracy                           0.98        63
   macro avg       0.98      0.99      0.98        63
weighted avg       0.99      0.98      0.98        63

