### Performance evaluation

 - Accuracy = fraction of correctly classified samples but not always a useful metric
 - Highly dependent on classes distribution ( a case of class imbalance, if 99% of the data is class A and 1% class B, a classifier predicting all data as class A would be highly accurate, but would not generalize well)
 - Confusion matrix: summarizes performance
 - Example
     - The class of interest is the "positive" class (what you are trying to predict, this case spam)
     - True positive: number of spams correctly labeled
     - True negative: number of real emails correctly labeled
     - False positive: number of real emails incorrectly classified as spams
     - False negative: number of spam emails incorrectly classified as real

<img src="ml_assets/conf_matrix.png" style="width: 500px;"/>

 - Accuracy is the sum of the diagonal (tp+tf) / sum of the matrix
 
 - Other metrics:
     - Precision = tp / tp + fp, also called positive predicted value (ppv)
             - emails correctly classified as spam / total emails classified as spam
             - high precision means low false positive rate, not many real emails are classified as spam
     - Recall = tp / tp + fn, also called sensitivity, hit rate or true positive rate
             - emails correctly classified as spam / total spam emails
             - high recall means not many spam emails are classified as real, most spams are classified as spams
     - F1 score = 2 * precision * recall / precision + recall
             - harmonic mean of precision and recall

In [7]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import load_wine

# Import KNeighborsClassifier from sklearn.neighbors
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import scale

# Import necessary modules
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [8]:
wines = load_wine()
features = pd.DataFrame(scale(wines['data']), columns = wines['feature_names'])
features.shape

(178, 13)

In [9]:
target = pd.DataFrame(wines['target'], columns=['Type'])
target.shape

(178, 1)

In [10]:
df = pd.concat([target,features],axis=1)
df.shape

(178, 14)

In [11]:
# Create arrays for the features and the response variable
y = target.values.reshape(-1)
X = features.values

In [12]:
# Create training and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state=42)

# Instantiate a k-NN classifier: knn
knn = KNeighborsClassifier(n_neighbors=6)

# Fit the classifier to the training data
knn.fit(X_train, y_train)

# Predict the labels of the test data: y_pred
y_pred = knn.predict(X_test)

# Generate the confusion matrix and classification report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


[[26  0  0]
 [ 5 22  0]
 [ 0  0 19]]
              precision    recall  f1-score   support

           0       0.84      1.00      0.91        26
           1       1.00      0.81      0.90        27
           2       1.00      1.00      1.00        19

    accuracy                           0.93        72
   macro avg       0.95      0.94      0.94        72
weighted avg       0.94      0.93      0.93        72



Model validation

Hyperparameter tuning